<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="Pages_Home" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server"><div class="text">Suntem incantati ca ai aflat despre <i>Check Inn Iasi</i> si suntem convinsi ca vei ramane mereu alaturi de noi. Dorim sa te cunoastem, sa ne adaptam dorintelor tale, sa asezi <i>Check Inn Iasi</i> in topul preferintelor tale.
<br />Pozitionat intr-o zona linistita ,<i>Check Inn Iasi</i> este locul in care puteti petrece timpul intr-un mod unic  de desfatare, fie ca va aflati in Iasi pentru un sejur de recreere, fie pentru a va ocupa de afacerea dumneavoastra. Localizat in partea nord-estica a capitalei Moldovei (Bd. Tudor Vladimirescu, nr. 46), <i>Check Inn Iasi</i>  va faciliteaza accesul in timp util(10 minute) catre zona centrala, la 2 minute de Manastirea Golia si 5 minute de ansamblul urbanistic Palas.
<br />Serviciile oferite sunt  gandite conform nevoilor dumneavoastra si se ridica la inaltii parametrii ai unei cazari impecabile. <i>Check Inn Iasi</i> dispune de 30 de camere moderne, dotate corespunzator, cu toate facilitatile de care aveti nevoie pentru a va simti confortabil. Ambianta camerelor face dovada bunului gust, constand in mobilier de calitate superioara, abundand in culori calde, care confera atmosfera propice relaxarii dumneavoastra.
<br />Ce ne face diferiti?<i>Check Inn Iasi</i> nu e doar o cladire in care va puteti petrece noptile departe de casa. Noi nu suntem un hotel rece, iar acest lucru ne face diferiti de alte hoteluri. Clientii nostri  stiu aceasta. Ei ne-au asezat deja in topul preferintelor lor gratie caldurii cu care-i intampinam si atentiei sporite pentru detalii.
<br />Ne deschidem cu drag usile, venind in intampinarea dumneavoastra cu caldura unei familii in care suntem dornici sa va integram. Iar in fiecare dimineata, va asteptam sa va alintam cu savuroasa aroma a cafelei Jacobs Alintaroma.<br /><br /><b>Va asteptam cu drag!</b><br /><br /><hr /><br /></div>
<div class="contact"><b>Informatii de contact:</b><br /><br />Adresa: Bd. Tudor Vladimirescu, nr. 46<br />Tel: 0742 024 393/0746 046 793<br />Fax: 0742 024 395<br />E-mail: rezervari@checkinniasi.ro/rezervari@check-inn.ro</div>
</asp:Content>

